wandb_version: 1

DANCE_SIZE:
  desc: null
  value: 51
DROPOUT:
  desc: null
  value: 0.1
D_K:
  desc: null
  value: 64
D_V:
  desc: null
  value: 64
MUSIC_SIZE:
  desc: null
  value: 439
_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1632588213
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.8.12
      5: 0.12.1
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 16
d_model:
  desc: null
  value: 240
data_dir:
  desc: null
  value: ../data2/
inner_d:
  desc: null
  value: 1024
lambda_v:
  desc: null
  value: 0.01
learningRate:
  desc: null
  value: 0.0001
maxEpochs:
  desc: null
  value: 5
n_heads:
  desc: null
  value: 8
n_layers:
  desc: null
  value: 2
